import Head from 'next/head'
import { server } from "../config"
import ArticleList from '../components/ArticleList'
// import styles from '../styles/Home.module.css'

export default function Home({ articles }) {
  return (
    <div>
      <Head>
        <title>Web dev news</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="web development, programming" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ArticleList articles={articles} />
     
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`${server}/api/articles`)
  const articles = await res.json()

  return {
    props: {
      articles,
    },
  }
}